### ISSUE TITLE
Create Main page

### ISSUE THREAD

**Issue by PaoGon** [PaoGon/R.I.M.#16]
### Tasks:
- [x] create list of report buttons
- [x] report forms
- [x] Map
- [x] Report pings
- [x] Area radius
- [x] cluster report pings when zoomed
- [x] Custom Pin Markers 
- [x] Info Window in each Markers
